alias ls="ls --color=auto"
alias grep="grep --color=auto"
alias clear="clear && echo 'So much depends on Red Wheelbarrow. Glazed with rainwater, beside the white chickens.'"
# alias etterna="~/games/Etterna-0.74.4-Linux/Etterna"
alias info="info --vi-keys"
alias ip="ip -c=auto"
# alias r2="r2 -e bin.relocs.apply=true"
alias update="sudo apt update && sudo apt full-upgrade && flatpak update"
alias vim="vim -i $XDG_STATE_HOME/vim/viminfo -u $XDG_CONFIG_HOME/vim/vimrc"
# alias wget="wget --hsts-file=~/.config/wget/wget-hsts"
