alias clear='clear && echo "So much depends on Red Wheelbarrow. Glazed with rainwater, beside the white chickens."'
alias etterna='~/games/Etterna-0.74.4-Linux/Etterna'
alias info='info --vi-keys'
alias pwntools='source ~/tools/pwntools/bin/activate'
alias r2='r2 -e bin.relocs.apply=true'
alias update='sudo apt update && sudo apt upgrade && flatpak update && yt-dlp -U && bw update && tldr -u'
alias vim='vim -i $XDG_STATE_HOME/vim/viminfo'
alias wget='wget --hsts-file=~/.config/wget/wget-hsts'
alias yt-dlp='python3 $(which yt-dlp)'
