" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

" Show matching characters.
set showmatch

syntax enable
" tab ball
set number relativenumber
set scrolloff=20
set tabstop=4
set expandtab
set showmode
set showmatch
set hlsearch
